stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:28.0.0
  services:
    - name: docker:dind-rootless
  tags:
    - MXL_dind
  parallel:
    matrix:
      - PRESET: ['Clang-Debug', 'Clang-Release', 'GCC-Debug', 'GCC-Release']
  variables:
    CI_PIPELINE_IID: $CI_PIPELINE_IID
    DOCKER_BUILDKIT: '1'
  before_script:
    - apk add bash
  script:
    - docker build -t mxl_build_container:$CI_PIPELINE_IID $CI_PROJECT_DIR/.devcontainer/
    - docker run --rm --volume $CI_PROJECT_DIR/:/workspace/mxl --volume $CI_PROJECT_DIR/vcpkg_cache:/home/devcontainer/.cache/vcpkg -i mxl_build_container:$CI_PIPELINE_IID cmake -S /workspace/mxl -B /workspace/mxl/build/Linux-$PRESET --preset Linux-$PRESET -DMXL_BUILD_NUMBER=$CI_PIPELINE_IID
    - docker run --rm --volume $CI_PROJECT_DIR/:/workspace/mxl --volume $CI_PROJECT_DIR/vcpkg_cache:/home/devcontainer/.cache/vcpkg -i mxl_build_container:$CI_PIPELINE_IID cmake --build /workspace/mxl/build/Linux-$PRESET -t all doc install package
    - docker run --rm --volume $CI_PROJECT_DIR/:/workspace/mxl --volume $CI_PROJECT_DIR/vcpkg_cache:/home/devcontainer/.cache/vcpkg -i mxl_build_container:$CI_PIPELINE_IID bash -c "cd /workspace/mxl/build/Linux-$PRESET && ctest --output-junit test-results.xml"
    - mv build/Linux-$PRESET/test-results.xml test-results-$PRESET.xml
  after_script:
    - docker rmi mxl_build_container:$CI_PIPELINE_IID || true
  cache:
    paths:
      - vcpkg_cache
  artifacts:
    paths:
      - install/Linux-$PRESET/
      - build/Linux-$PRESET/*.deb
    reports:
      junit: test-results-$PRESET.xml

